language: node_js

cache:
  directories:
    - "node_modules"

script:
  - npm test

# deploy:
#   - provider: npm
#     skip_cleanup: true
#     email: ""
#     api_key:
#       secure: ""
#     on:
#       tags: true
